# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59d0de0aa8c587b5138203918e596f9fa97a5d9778b1a1f75ba93031c250b90c43cbecf0163f6d5029c742b5270bce1ef7232575e34480f11954455e17119fd2

test:
  secret_key_base: cb2337c26081e3417a6bae80eb342fffa254eee947975d7c643fb9f963b3ffc41a462524dea40d2f65209b181556733f6e318d046456b622e4465e43ccdc1c38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
